spring:
  # database connection set
  # first try: jdbc:h2:~/jpashop
  # after: jdbc:h2:tcp://localhost/~/jpashop
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create    # table drop and restart
    properties:
      hibernate:
#        show_sql: true  # print using 'System.out.print()'
        format_sql: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect  # default인데 오류 발생
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug  # hibernate execution SQL using 'logger'
#  org.hibernate.type: trace  # show you "Query Parameter"
  org.springframework.web: debug
